services:
  droplet-api:
    build: 
      context: src/
    env_file:
      - src/.env
    restart: unless-stopped
    container_name: droplet-api
    environment:
      - TZ=Europe/London
    ports:
      - 5959:5959
    healthcheck:
        test: curl --fail http://localhost:5959/api/v1 || exit 1
        interval: 40s
        timeout: 30s
        retries: 3
        start_period: 60s